### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by weishwu** [julienrichardalbert/MEA#14]
Hi,

I downloaded the MEA docker file and installed the docker image. Then I followed the manual and ran the command-line below:

```
export MEA='docker run -v /nfs/med-bfx-activeprojects/weishwu/common/MEA/dist/mea/bin:/mea-data -i weishwu/mea:1.0'
```

Then I ran

```
$MEA setting
```

But this gave me an error saying:

```
docker: Error response from daemon: error while creating mount source path '/nfs/med-bfx-activeprojects/weishwu/common/MEA/dist/mea/bin': mkdir /nfs/med-bfx-activeprojects/weishwu: permission denied.
ERRO[0001] error waiting for container: context canceled
```

Any help? Thanks.

**Comment by biscuit13161** [comment]
Hi,

I've not tried converting the docker image to singularity ... but I notice
that you haven't defined a mount point in your second and third binds.

I think you need to either

   - provide a mount point that exists in the image to bind to and use that
   mount point in your command
   - don't use the second and third "-B" and  use the full path in the
   command

also, I've never seen the binds quoted in singularity commands, so it might be worth trying it without the quotes.

HTH but let us know if it's still an issue.

Richard

**Comment by weishwu** [comment]
Hi Richard,

Thanks for the response. I actually edited my question after I posted it. It seemed I edited it before you answered my original post.

I tried using Docker but got a permission error (which was why I switched to using Singularity):

```
export MEA='docker run -v /nfs/med-bfx-activeprojects/weishwu/common/MEA/dist/mea/bin:/mea-data -i weishwu/mea:1.0'
```

Then I ran

```
$MEA setting
```

But this gave me an error saying:

```
docker: Error response from daemon: error while creating mount source path '/nfs/med-bfx-activeprojects/weishwu/common/MEA/dist/mea/bin': mkdir /nfs/med-bfx-activeprojects/weishwu: permission denied.
ERRO[0001] error waiting for container: context canceled
```

Any help? Thanks.

**Comment by weishwu** [comment]
Hi Richard,

Thanks for your quick answer. I got the same error now by using docker:

```
export MEA='docker run -v /nfs/mm-isilon/bioinfcore/ActiveProjects/weishwu/common/MEA/dist/mea/bin/:/mea-data -i weishwu/mea:1.0'

${MEA} createGenome /mea-data/Homo_sapiens_assembly38.fasta /mea-data/test.vcf strain1 strain2 /mea-data/test
```

Error message:
```
[mea] [createGenome] Started at [Tue Dec 29 02:31:12 UTC 2020]
Error: File undefined does not exist
```

**Comment by weishwu** [comment]
Never mind. I got it.
