### ISSUE TITLE
Not correct sed for chrom.sizes file

### ISSUE THREAD

**Issue by michael-kotliar** [julienrichardalbert/MEA#2]
Is this is correct?
```sed -i 's/>chr/>/g' "$BUILD".chrom.sizes```
It looks like this should be changed to
```sed -i 's/chr//g' "$BUILD".chrom.sizes```

https://github.com/julienrichardalbert/MEA/blob/master/src/scripts/setting.sh#L45

**Comment by julienrichardalbert** [comment]
That is indeed what was intended, thank you for proposing the correct fix too!
