### ISSUE TITLE
There is no way to limit memory use and set threads number

### ISSUE THREAD

**Issue by michael-kotliar** [julienrichardalbert/MEA#3]
I believe user should be allowed to allocate computational resources by himself. And if they are not set, use defaults.

[mea.config](https://github.com/julienrichardalbert/MEA/blob/aeece1a4cb800f791b9b8c4c85765dccd0638f07/src/scripts/mea.config#L89)
```
# Total CPUs on machine
global_cpus_tmp=$(grep -c ^processor /proc/cpuinfo)
# 95% of all CPUs
global_cpus=$(echo "scale=0;$global_cpus_tmp-($global_cpus_tmp/20)" | bc)
# 95% of all RAM on machine
global_mem=$[950 * $(awk '/^MemTotal:/{print $2}' /proc/meminfo)]

MEA_THREADS=$global_cpus
MEA_THREAD_MEM=$global_mem
```
[createGenome.sh](https://github.com/julienrichardalbert/MEA/blob/aeece1a4cb800f791b9b8c4c85765dccd0638f07/src/scripts/createGenome.sh#L72)
```
local cpus_tmp=$(grep -c ^processor /proc/cpuinfo)
local cpus=$(echo "scale=0;$cpus_tmp-($cpus_tmp/15)" | bc)
```

**Comment by julienrichardalbert** [comment]
We considered implementing allowing users to allocate resources, it is a good idea.
However, we designed MEA for people with little to no computer knowledge, so manual allocation of resources was not considered. I will add it to the TODO list.  
For createGenome.sh which only has to be run once for any given F1 hybrid, we worked under the assumption that MEA is the only program running for the few hours it takes to create a pseudogenome and index. Will warn users of this assumption now..
