### ISSUE TITLE
Hardcoded limitation for Java Virtual Machine

### ISSUE THREAD

**Issue by michael-kotliar** [julienrichardalbert/MEA#4]
[MEA_BIN_MEA="$MEA_BIN_JAVA -Xms4G -Xmx8G -jar $MEA_DIR_TOOLS/alea.jar"](https://github.com/julienrichardalbert/MEA/blob/aeece1a4cb800f791b9b8c4c85765dccd0638f07/src/scripts/mea.config#L56)
causes the following error
`java.lang.OutOfMemoryError: GC overhead limit exceeded` because `-Xmx8G` is too small

**Comment by julienrichardalbert** [comment]
While I do not know how to dynamically assign JVM max heap size, I am increasing it to 54G as this is the MEA recommended RAM size. Please let me know if this is not an appropriate fix and I will try harder

**Comment by michael-kotliar** [comment]
This is how you can dynamically change Xms and Xms values
```
#!/bin/bash
JAVA_XMS=${JAVA_XMS:=4G}
JAVA_XMX=${JAVA_XMX:=54G}
ALEA_JAR="java -Xms$JAVA_XMS -Xmx$JAVA_XMX -jar alea.jar"
echo $ALEA_JAR
```
Running the script, when environmental variables `JAVA_XMS` and `JAVA_XMX` are not set will give you output
```
java -Xms4G -Xmx54G -jar alea.jar
```
If you set these variables
```
export JAVA_XMS="8G"
export JAVA_XMX="120G"
```
it will give you output
```
java -Xms8G -Xmx120G -jar alea.jar
```
