### ISSUE TITLE
Two different versions of samtools

### ISSUE THREAD

**Issue by michael-kotliar** [julienrichardalbert/MEA#5]
Why does MEA requires two versions of samtools?

- samtools-0.1.19
- samtools-1.3.1

Can I run it only with the latest version of samtools?

**Comment by julienrichardalbert** [comment]
Samtools changed output file naming conventions between versions. As a result,  we use 1.3.1 for updated samtools libraries but stick with the legacy 0.1.19 to keep file naming consistency. It will run with the latest samtools but will require some file name altering.

**Comment by michael-kotliar** [comment]
Ok, thank you for explanation
